use_frameworks!

target 'SimpleChatIOS' do
  platform :ios, '9.0'
  pod 'sReto/AllModules', :path => '../../'
end

target 'SimpleChatMac' do
  platform :osx, '10.9'
  pod 'sReto/AllModules', :path => '../../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
