use_frameworks!

target :sRetoIOS do
  platform :ios, '9.0'
  pod 'CocoaAsyncSocket', '7.5.1'
  pod 'SocketRocket', '0.4.2'
  
  target :sRetoTests do
  end
    
end

target :sRetoMac do
  platform :osx, '10.9'
  pod 'CocoaAsyncSocket', '7.5.1'
  pod 'SocketRocket', '0.4.2'
end