use_frameworks!

target :sRetoIOS do
  platform :ios, '8.0'
  pod 'CocoaAsyncSocket', '7.4.2'
  pod 'SocketRocket', '0.4.2'
  link_with 'sRetoTests'  
end

target :sRetoMac do
  platform :osx, '10.9'
  pod 'CocoaAsyncSocket', '7.4.2'
  pod 'SocketRocket', '0.4.2'
end